from __future__ import annotations

"""Build a reviewer-facing baseline robustness artifact."""

import argparse
import json
from pathlib import Path
from typing import Any


ROOT_PATH = Path(__file__).resolve().parent.parent

TRACKS = (
    {
        "track": "contradiction",
        "leaderboard": Path("leaderboard/leaderboard_v0_1_1.json"),
        "task_aware": "ContradictionEngine",
        "low_information": "HashPriorBaseline",
    },
    {
        "track": "contradiction-adversarial",
        "leaderboard": Path("leaderboard/leaderboard_adversarial_v0_2_0.json"),
        "task_aware": "ContradictionEngine",
        "low_information": "HashPriorBaseline",
    },
    {
        "track": "contradiction-multihop",
        "leaderboard": Path("leaderboard/leaderboard_multihop_v0_3_0.json"),
        "task_aware": "ContradictionEngine",
        "low_information": "HashPriorBaseline",
    },
    {
        "track": "contradiction-controls",
        "leaderboard": Path("leaderboard/leaderboard_controls_v0_4_0.json"),
        "task_aware": "ContradictionEngine",
        "low_information": "HashPriorBaseline",
    },
)

EXPECTED_LOW_INFORMATION_WATCHLIST = {
    "contradiction-multihop": (
        "HashPriorBaseline currently outranks ContradictionEngine; treat this as a "
        "baseline-robustness watchlist item before expanding the multi-hop track"
    ),
}


def run_baseline_robustness(root: Path = ROOT_PATH) -> tuple[list[dict[str, Any]], list[str]]:
    results: list[dict[str, Any]] = []
    failures: list[str] = []

    for track in TRACKS:
        leaderboard_path = Path(track["leaderboard"])
        leaderboard = _read_json(root / leaderboard_path)
        entries = {
            str(entry.get("system_name")): entry
            for entry in leaderboard.get("entries", [])
            if isinstance(entry, dict)
        }
        task_aware = entries.get(str(track["task_aware"]))
        low_information = entries.get(str(track["low_information"]))
        track_name = str(track["track"])

        if task_aware is None:
            failures.append(f"{track_name}: missing task-aware baseline {track['task_aware']}")
            continue
        if low_information is None:
            failures.append(f"{track_name}: missing low-information baseline {track['low_information']}")
            continue

        task_rank = int(task_aware.get("rank", 0))
        low_rank = int(low_information.get("rank", 0))
        low_information_ahead = low_rank < task_rank
        expected_note = EXPECTED_LOW_INFORMATION_WATCHLIST.get(track_name)

        if low_information_ahead and expected_note is None:
            failures.append(f"{track_name}: low-information baseline unexpectedly outranks task-aware baseline")
        if not low_information_ahead and expected_note is not None:
            failures.append(f"{track_name}: watchlist entry is stale; low-information baseline no longer outranks")

        results.append(
            {
                "track": track_name,
                "leaderboard": leaderboard_path.as_posix(),
                "task_aware": str(track["task_aware"]),
                "task_aware_rank": task_rank,
                "task_aware_score": float(task_aware.get("overall_score", 0.0)),
                "low_information": str(track["low_information"]),
                "low_information_rank": low_rank,
                "low_information_score": float(low_information.get("overall_score", 0.0)),
                "status": "watchlist" if low_information_ahead else "pass",
                "note": expected_note or "low-information baseline does not outrank task-aware baseline",
            }
        )

    return results, failures


def build_baseline_robustness_artifact(results: list[dict[str, Any]], failures: list[str]) -> str:
    status = "PASS" if not failures else "FAIL"
    lines = [
        "# Baseline Robustness Snapshot",
        "",
        f"Overall status: {status}",
        "",
        "This artifact is generated by:",
        "",
        "```bash",
        "python scripts/check_baseline_robustness.py --artifact docs/BASELINE_ROBUSTNESS.md",
        "```",
        "",
        "Low-information baselines are useful diagnostic references, but they should not be mistaken for task-aware systems.",
        "If a low-information baseline outranks the packaged task-aware baseline, the track is listed as a watchlist item.",
        "",
        "## Track summary",
        "",
        "| Track | Task-aware rank | Task-aware score | Low-information rank | Low-information score | Status | Note |",
        "| --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for item in results:
        lines.append(
            "| {track} | {task_aware_rank} | {task_aware_score:.2f} | "
            "{low_information_rank} | {low_information_score:.2f} | {status} | {note} |".format(**item)
        )

    if failures:
        lines.extend(["", "## Failures", ""])
        for failure in failures:
            lines.append(f"- {failure}")

    return "\n".join(lines) + "\n"


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return data


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run baseline robustness diagnostics.")
    parser.add_argument(
        "--artifact",
        default=None,
        help="Optional output path for a reviewer-facing baseline robustness artifact.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    results, failures = run_baseline_robustness()

    if args.artifact:
        Path(args.artifact).parent.mkdir(parents=True, exist_ok=True)
        Path(args.artifact).write_text(build_baseline_robustness_artifact(results, failures), encoding="utf-8")

    for failure in failures:
        print(f"ERROR: {failure}")

    if failures:
        return 1
    print("Baseline robustness checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
