from __future__ import annotations

"""Run lightweight scoring sanity checks for benchmark reports."""

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT_PATH = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_PATH))

from marked_bench.benchmark_scoring_spec import SCORE_WEIGHTS
from marked_bench.contradiction.benchmark_suite import evaluate_standard_suite

SUITE_CHECKS: tuple[str, ...] = (
    "contradiction-v0.1.0",
    "contradiction",
    "contradiction-adversarial",
    "contradiction-multihop",
    "contradiction-controls",
)


def _expected_overall_score(report: dict[str, Any]) -> float:
    metrics = report["metrics"]
    return round(
        100
        * (
            SCORE_WEIGHTS["contradiction_macro_f1"] * metrics["contradiction_macro_f1"]
            + SCORE_WEIGHTS["type_accuracy"] * metrics["type_accuracy"]
            + SCORE_WEIGHTS["binary_detection_f1"] * metrics["detection"]["f1"]
            + SCORE_WEIGHTS["coverage_index"] * metrics["coverage_index"]
        ),
        2,
    )


def _check_report(report: dict[str, Any], tag: str) -> tuple[bool, list[str]]:
    errors: list[str] = []

    try:
        score = float(report["overall_score"])
    except Exception:
        errors.append(f"{tag}: overall_score missing or not numeric")
        return False, errors

    if not (0.0 <= score <= 100.0):
        errors.append(f"{tag}: overall_score outside [0, 100]: {score}")

    expected = _expected_overall_score(report)
    if score != expected:
        errors.append(f"{tag}: overall_score mismatch: expected {expected}, got {score}")

    if report.get("case_count", 0) <= 0:
        errors.append(f"{tag}: case_count must be positive")

    metrics = report.get("metrics", {})
    for metric in ("contradiction_macro_f1", "type_accuracy", "coverage_index"):
        if not (0.0 <= float(metrics.get(metric, -1.0)) <= 1.0):
            errors.append(f"{tag}: {metric} must be within [0, 1]")

    detection = metrics.get("detection", {})
    for metric in ("precision", "recall", "f1", "accuracy"):
        if not (0.0 <= float(detection.get(metric, -1.0)) <= 1.0):
            errors.append(f"{tag}: detection.{metric} must be within [0, 1]")

    return (not errors), errors


def run_scoring_sanity() -> tuple[list[dict[str, Any]], list[str]]:
    results: list[dict[str, Any]] = []
    errors: list[str] = []

    for suite in SUITE_CHECKS:
        strong = evaluate_standard_suite(suite=suite, system_name=f"{suite}-strong")
        weak = evaluate_standard_suite(
            lambda _claim: None,
            suite=suite,
            system_name=f"{suite}-weak",
        )
        if weak["overall_score"] >= strong["overall_score"]:
            errors.append(f"{suite}: weak score >= strong score ({weak['overall_score']} >= {strong['overall_score']})")

        strong_ok, strong_errors = _check_report(strong, f"{suite}:strong")
        weak_ok, weak_errors = _check_report(weak, f"{suite}:weak")
        errors.extend(strong_errors)
        errors.extend(weak_errors)

        results.append(
            {
                "suite": suite,
                "suite_id": strong["suite_id"],
                "suite_version": strong["suite_version"],
                "case_count": strong["case_count"],
                "strong_score": strong["overall_score"],
                "weak_score": weak["overall_score"],
                "spread": round(strong["overall_score"] - weak["overall_score"], 2),
                "status": "pass" if strong_ok and weak_ok else "fail",
                "strong_validation_ok": strong_ok,
                "weak_validation_ok": weak_ok,
            }
        )

    return results, errors


def build_scoring_sanity_artifact(results: list[dict[str, Any]], failures: list[str]) -> str:
    status = "PASS" if not failures else "FAIL"
    lines = [
        "# Scoring Sanity Snapshot",
        "",
        f"Overall status: {status}",
        "",
        "This artifact is generated by:",
        "",
        "```bash",
        "python scripts/check_scoring_sanity.py --artifact docs/SCORING_SANITY.md",
        "```",
        "",
        "## Suite checks",
        "",
        "| Suite | Suite Version | Case Count | Strong Score | Weak Score | Spread | Formula check |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- |",
    ]

    for item in results:
        status_text = "pass" if item["strong_validation_ok"] and item["weak_validation_ok"] else "fail"
        row = {
            "suite": item["suite"],
            "suite_version": item["suite_version"],
            "case_count": item["case_count"],
            "strong_score": item["strong_score"],
            "weak_score": item["weak_score"],
            "spread": item["spread"],
            "status_text": status_text,
        }
        lines.append(
            "| {suite} | `{suite_version}` | {case_count} | {strong_score:.2f} | {weak_score:.2f} | {spread:.2f} | {status_text} |".format(**row)
        )

    if failures:
        lines.extend(
            [
                "",
                "## Failures",
                "",
            ]
        )
        for failure in failures:
            lines.append(f"- {failure}")

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a scoring sanity sweep over representative suites.")
    parser.add_argument(
        "--artifact",
        default=None,
        help="Optional output path for a reviewer-facing scoring sanity artifact.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    results, failures = run_scoring_sanity()

    if args.artifact:
        Path(args.artifact).parent.mkdir(parents=True, exist_ok=True)
        Path(args.artifact).write_text(build_scoring_sanity_artifact(results, failures), encoding="utf-8")

    for failure in failures:
        print(f"ERROR: {failure}")

    if failures:
        return 1
    print("Scoring sanity checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
