from __future__ import annotations

"""Build a lightweight case-quality diagnostic artifact for public suites."""

import argparse
from difflib import SequenceMatcher
from pathlib import Path
import sys
from typing import Any

ROOT_PATH = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_PATH))

from marked_bench.contradiction.benchmark_suite import build_suite_manifest


SUITE_CHECKS: tuple[str, ...] = (
    "contradiction-v0.1.0",
    "contradiction",
    "contradiction-adversarial",
    "contradiction-multihop",
    "contradiction-controls",
)

KNOWN_NEAR_DUPLICATE_NOTES = {
    frozenset({"marked-hop-property-002", "marked-hop-property-003"}): (
        "intentional contrast between an inherited unit conflict and a same-unit context control"
    ),
    frozenset({"marked-hop-universal-001", "marked-hop-universal-003"}): (
        "intentional contrast between a universal counterexample and a non-universal control"
    ),
}


def run_case_quality() -> tuple[list[dict[str, Any]], list[str]]:
    results: list[dict[str, Any]] = []
    failures: list[str] = []

    for suite in SUITE_CHECKS:
        manifest = build_suite_manifest(suite=suite)
        profile = manifest["profile"]
        duplicate_pairs = _near_duplicate_pairs(manifest["cases"])
        failed_gates = [
            name
            for name, value in profile["quality_gates"].items()
            if name != "min_cases" and value is not True
        ]
        if manifest["case_count"] < int(profile["quality_gates"]["min_cases"]):
            failed_gates.append("min_cases")
        if failed_gates:
            failures.append(f"{suite}: failed quality gates: {', '.join(sorted(failed_gates))}")

        results.append(
            {
                "suite": suite,
                "suite_id": manifest["suite_id"],
                "suite_version": manifest["suite_version"],
                "case_count": manifest["case_count"],
                "contradiction_case_count": profile["contradiction_case_count"],
                "control_case_count": profile["control_case_count"],
                "label_count": len(profile["label_counts"]),
                "domain_count": len(profile["domain_counts"]),
                "difficulty_count": len(profile["difficulty_counts"]),
                "capability_count": len(profile["capability_counts"]),
                "tag_count": len(profile["tag_counts"]),
                "near_duplicate_count": len(duplicate_pairs),
                "near_duplicates": duplicate_pairs,
                "status": "pass" if not failed_gates else "fail",
            }
        )

    return results, failures


def build_case_quality_artifact(results: list[dict[str, Any]], failures: list[str]) -> str:
    status = "PASS" if not failures else "FAIL"
    lines = [
        "# Case Quality Snapshot",
        "",
        f"Overall status: {status}",
        "",
        "This artifact is generated by:",
        "",
        "```bash",
        "python scripts/check_case_quality.py --artifact docs/CASE_QUALITY.md",
        "```",
        "",
        "## Suite composition",
        "",
        "| Suite | Version | Cases | Contradictions | Controls | Domains | Capabilities | Near-duplicate pairs | Status |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for item in results:
        lines.append(
            "| {suite} | `{suite_version}` | {case_count} | {contradiction_case_count} | "
            "{control_case_count} | {domain_count} | {capability_count} | "
            "{near_duplicate_count} | {status} |".format(**item)
        )

    duplicate_items = [
        (item["suite"], pair)
        for item in results
        for pair in item["near_duplicates"]
    ]
    if duplicate_items:
        lines.extend(["", "## Near-duplicate watchlist", ""])
        for suite, pair in duplicate_items:
            lines.append(
                "- {suite}: `{left}` and `{right}` similarity={similarity:.3f}; note={note}".format(
                    suite=suite,
                    **pair,
                )
            )

    if failures:
        lines.extend(["", "## Failures", ""])
        for failure in failures:
            lines.append(f"- {failure}")

    return "\n".join(lines) + "\n"


def _near_duplicate_pairs(cases: list[dict[str, Any]], threshold: float = 0.96) -> list[dict[str, Any]]:
    pairs: list[dict[str, Any]] = []
    for left_index, left in enumerate(cases):
        for right in cases[left_index + 1 :]:
            similarity = SequenceMatcher(None, _case_text(left), _case_text(right)).ratio()
            if similarity >= threshold:
                pairs.append(
                    {
                        "left": str(left["id"]),
                        "right": str(right["id"]),
                        "similarity": round(similarity, 3),
                        "note": KNOWN_NEAR_DUPLICATE_NOTES.get(
                            frozenset({str(left["id"]), str(right["id"])}),
                            "review required",
                        ),
                    }
                )
    return pairs


def _case_text(case: dict[str, Any]) -> str:
    return f"{case.get('premise', '')} {case.get('query', '')}".lower()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run case-quality diagnostics over public suites.")
    parser.add_argument(
        "--artifact",
        default=None,
        help="Optional output path for a reviewer-facing case-quality artifact.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    results, failures = run_case_quality()

    if args.artifact:
        Path(args.artifact).parent.mkdir(parents=True, exist_ok=True)
        Path(args.artifact).write_text(build_case_quality_artifact(results, failures), encoding="utf-8")

    for failure in failures:
        print(f"ERROR: {failure}")

    if failures:
        return 1
    print("Case quality checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
